apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: k8s-getsecret
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/mariusciotir/k8s-getsecret.git
      revision: main
      directories:
      - path: helm/k8s-getsecret
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/mariusciotir/k8s-getsecret.git
        path: '{{path}}'
        targetRevision: main
        helm:
          valueFiles:
          - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: k8s-getsecret
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
